#!/bin/bash

# TODO: Validate input

RELEASE_NUMBER=$1
RELEASE_NAME=$2
RELEASE_SERIES="[SERIES]"
RELEASE_DATE="[DATE]"
RELEASE_DESC=""
WAYLAND_ANNOUNCE_LINK="http://lists.freedesktop.org/archives/wayland-devel/[link here]"
WESTON_ANNOUNCE_LINK="http://lists.freedesktop.org/archives/wayland-devel/[link here]"

echo "<h3>${RELEASE_NUMBER} Release</h3>"

if [ "${RELEASE_NAME}" = "alpha" ]; then
	echo "This is the alpha for Wayland and Weston ${RELEASE_SERIES}."
	echo "It was released on ${RELEASE_DATE}."
elif [ "${RELEASE_NAME}" = "beta" ]; then
	echo "This is the beta for Wayland and Weston ${RELEASE_SERIES}."
	echo "It was released on ${RELEASE_DATE}."
elif [ "${RELEASE_NAME}" = "RC1" ]; then
	echo "This is the first release candidate for ${RELEASE_SERIES}."
	echo "<p>${RELEASE_NAME} for Wayland and Weston was released on ${RELEASE_DATE}."
elif [ "${RELEASE_NAME}" = "RC2" ]; then
	echo "This is the second release candidate for ${RELEASE_SERIES}."
	echo "<p>${RELEASE_NAME} for Wayland and Weston was released on ${RELEASE_DATE}."
else
	echo "<p>${RELEASE_NAME} for Wayland and Weston was released on ${RELEASE_DATE}."
fi

cat <<EOF
<ul>
<li><a href="releases/wayland-${RELEASE_NUMBER}.tar.xz">wayland-${RELEASE_NUMBER}.tar.xz</a> -
  - <a href="${WAYLAND_ANNOUNCE_LINK}">Wayland ${RELEASE_NUMBER} Release Announcement</a></li>
<li><a href="releases/weston-${RELEASE_NUMBER}.tar.xz">weston-${RELEASE_NUMBER}.tar.xz</a>
  - <a href="${WESTON_ANNOUNCE_LINK}">Weston ${RELEASE_NUMBER} Release Announcement</a></li>
</ul>
EOF
