#!/bin/bash

# TODO: Validate input

RELEASE_NUMBER=$1
RELEASE_NAME=$2
RELEASE_SERIES="[SERIES]"
RELEASE_DATE="[DATE]"
RELEASE_DESC=""

announcements=$(wl_get_announcements)
wayland_announce_link=$(echo "$announcements" | grep "wayland $RELEASE_NUMBER" | cut -d' ' -f3)
weston_announce_link=$(echo "$announcements" | grep "weston $RELEASE_NUMBER" | cut -d' ' -f3)

echo "<h3>${RELEASE_DATE}</h3>"

echo "<p>"
if [ "${RELEASE_NAME}" = "alpha" ]; then
	echo "The ${RELEASE_NAME} for Wayland and Weston ${RELEASE_SERIES},"
	echo "version ${RELEASE_NUMBER}, was released."
elif [ "${RELEASE_NAME}" = "beta" ]; then
	echo "This is the beta for Wayland and Weston ${RELEASE_SERIES}."
	echo "It was released on ${RELEASE_DATE}."
elif [ "${RELEASE_NAME}" = "RC1" ]; then
	echo "This is the first release candidate for ${RELEASE_SERIES}."
	echo "<p>${RELEASE_NAME} for Wayland and Weston was released on ${RELEASE_DATE}."
elif [ "${RELEASE_NAME}" = "RC2" ]; then
	echo "This is the second release candidate for ${RELEASE_SERIES}."
	echo "<p>${RELEASE_NAME} for Wayland and Weston was released on ${RELEASE_DATE}."
else
	echo "<p>${RELEASE_NAME} for Wayland and Weston was released on ${RELEASE_DATE}."
fi
echo "</p>"

cat <<EOF
<ul>
<li><a href="releases/wayland-${RELEASE_NUMBER}.tar.xz">wayland-${RELEASE_NUMBER}.tar.xz</a> -
  - <a href="${wayland_announce_link}">Wayland ${RELEASE_NUMBER} Release Announcement</a></li>
<li><a href="releases/weston-${RELEASE_NUMBER}.tar.xz">weston-${RELEASE_NUMBER}.tar.xz</a>
  - <a href="${weston_announce_link}">Weston ${RELEASE_NUMBER} Release Announcement</a></li>
</ul>
EOF
