#!/bin/bash

# TODO: Validate input

RELEASE_NUMBER=$1
RELEASE_SERIES="[SERIES]"
RELEASE_DESC=""

announcements=$(wl_get_announcements)
wayland_announce_link=$(echo "$announcements" | grep "wayland $RELEASE_NUMBER" | cut -d' ' -f3)
weston_announce_link=$(echo "$announcements" | grep "weston $RELEASE_NUMBER" | cut -d' ' -f3)

if [ "${RELEASE_NUMBER##*.}" = "91" ]; then
    release_name=alpha
elif [ "${RELEASE_NUMBER##*.}" = "92" ]; then
    release_name=beta
elif [ "${RELEASE_NUMBER##*.}" = "93" ]; then
    release_name=rc
elif [ "${RELEASE_NUMBER##*.}" = "0" ]; then
    release_name=official
elif [ "${RELEASE_NUMBER##*.}" = "1" ]; then
    release_name=point
elif [ "${RELEASE_NUMBER##*.}" = "2" ]; then
    release_name=point
elif [ "${RELEASE_NUMBER##*.}" = "3" ]; then
    release_name=point
else
    echo "Error: Can't figure out release name from version number.  FIXME."
    exit 1
fi

# Lookup release date
weston_announce_text=$(wget -q -O- "${weston_announce_link}")
announce_time=$(echo "${weston_announce_text}" | grep "<I>" | head -n1 | sed -e 's/ *<I>\(.*\)<\/I>/\1/')
release_date=$(date -d "$announce_time" +"%B %d, %Y")

echo "<h3>${release_date}</h3>"
echo

echo "<p>"
if [ "${release_name}" = "alpha" ]; then
	echo "The ${release_name} for Wayland and Weston ${RELEASE_SERIES},"
	echo "version ${RELEASE_NUMBER}, was released."
elif [ "${release_name}" = "beta" ]; then
	echo "This is the beta for Wayland and Weston ${RELEASE_SERIES}."
	echo "It was released on ${RELEASE_DATE}."
elif [ "${release_name}" = "RC1" ]; then
	echo "This is the first release candidate for ${RELEASE_SERIES}."
	echo "<p>${release_name} for Wayland and Weston was released on ${RELEASE_DATE}."
elif [ "${release_name}" = "RC2" ]; then
	echo "This is the second release candidate for ${RELEASE_SERIES}."
	echo "<p>${release_name} for Wayland and Weston was released on ${RELEASE_DATE}."
else
	echo "<p>${release_name} for Wayland and Weston was released on ${RELEASE_DATE}."
fi
echo "</p>"
echo

cat <<EOF
<ul>
<li><a href="releases/wayland-${RELEASE_NUMBER}.tar.xz">wayland-${RELEASE_NUMBER}.tar.xz</a> -
  - <a href="${wayland_announce_link}">Wayland ${RELEASE_NUMBER} Release Announcement</a></li>
<li><a href="releases/weston-${RELEASE_NUMBER}.tar.xz">weston-${RELEASE_NUMBER}.tar.xz</a>
  - <a href="${weston_announce_link}">Weston ${RELEASE_NUMBER} Release Announcement</a></li>
</ul>
EOF
echo
